/**
 * DashboardUser.java
 * Esta clase representa la interfaz de usuario para el panel de control de administrador de la aplicación.
 * Permite a los administradores acceder a diferentes funcionalidades, como la gestión de usuarios,
 * productos, proveedores, generación de reportes, y proporciona opciones de navegación en el menú.
 * Incluso, muestra información del usuario, productos, proveedores y la fecha actual en el encabezado.
 *
 * Este archivo es parte de InversionesRT.
 *
 * InversionesRT es software libre: puedes redistribuirlo y/o modificarlo
 * bajo los términos de la Licencia Pública General GNU publicada por
 * la Free Software Foundation, ya sea la versión 3 de la Licencia, o
 * (a su elección) cualquier versión posterior.
 *
 * InversionesRT se distribuye con la esperanza de que sea útil,
 * pero SIN NINGUNA GARANTÍA; incluso sin la garantía implícita de
 * COMERCIABILIDAD o APTITUD PARA UN PROPÓSITO PARTICULAR. Consulta la
 * Licencia Pública General GNU para más detalles.
 *
 * Deberías haber recibido una copia de la Licencia Pública General GNU
 * junto con [nombre del proyecto]. En caso contrario, consulta
 * <https://www.gnu.org/licenses/gpl-3.0.html>.
 */
package com.menu;

import com.clase.bd.Conexion;
import com.views.*;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.login.Login;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.WindowConstants;

public class DashboardUser extends javax.swing.JFrame {

    String user, nombre, apellido;
    public static int sesionUsuario;

    public DashboardUser() {
        initComponents();
        initStyles();
        setDate();
        initContent();
        nameUser();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    // Busca el nombre de usuario y su apellido en MySQL y lo muestra en el Dashboard.
    private void nameUser() {
        user = Login.user;
        sesionUsuario = 1;
        setTitle("Acceso de Usuario");

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT nombre, apellido FROM usuario WHERE username = '" + user + "'");

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                nombre = rs.getString("nombre");
                apellido = rs.getString("apellido");
                tituloBienvenido.setText("¡Bienvenido(a) " + nombre + " " + apellido + "!");
            }

        } catch (Exception e) {
            System.err.println("Error en la conexión desde la interfaz Usuario");
        }
    }

    // Estilos que establecen los estilos de tipografía y color de los títulos del panel menú y header.
    private void initStyles() {
        tituloBienvenido.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        tituloBienvenido.setForeground(Color.WHITE);

        tituloDate.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        tituloDate.setForeground(Color.WHITE);

        nombreEmpresa.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        nombreEmpresa.setForeground(Color.WHITE);
    }

    // Función que recoge la fecha actual del sistema y lo muestra.
    private void setDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        tituloDate.setText(now.format(DateTimeFormatter.ofPattern(" 'Hoy es' EEEE dd 'de' MMMM"
                + " 'de' yyyy", spanishLocale)));
    }

    private void initContent() {
        ShowJPanel(new Principal());
    }

    private static void ShowJPanel(JPanel p) {
        p.setSize(750, 490);
        p.setLocation(0, 0);

        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        nombreEmpresa = new javax.swing.JLabel();
        separadorEmpresa = new javax.swing.JSeparator();
        separadorEmpresaUltimo = new javax.swing.JSeparator();
        botonPrincipal = new javax.swing.JButton();
        botonUsuario = new javax.swing.JButton();
        botonProducto = new javax.swing.JButton();
        botonProveedor = new javax.swing.JButton();
        botonReporte = new javax.swing.JButton();
        botonAcercaDe = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        tituloBienvenido = new javax.swing.JLabel();
        tituloDate = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 670));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(0, 0, 0));

        menu.setBackground(new java.awt.Color(90, 58, 201));
        menu.setForeground(new java.awt.Color(0, 0, 0));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        nombreEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        nombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreEmpresa.setText("Inversiones R.T");

        separadorEmpresa.setBackground(new java.awt.Color(0, 0, 0));
        separadorEmpresa.setForeground(new java.awt.Color(255, 255, 255));

        separadorEmpresaUltimo.setBackground(new java.awt.Color(0, 0, 0));
        separadorEmpresaUltimo.setForeground(new java.awt.Color(255, 255, 255));

        botonPrincipal.setBackground(new java.awt.Color(141, 114, 231));
        botonPrincipal.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        botonPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        botonPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/casa.png"))); // NOI18N
        botonPrincipal.setText("Principal");
        botonPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        botonPrincipal.setBorderPainted(false);
        botonPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonPrincipal.setIconTextGap(15);
        botonPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrincipalActionPerformed(evt);
            }
        });

        botonUsuario.setBackground(new java.awt.Color(141, 114, 231));
        botonUsuario.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        botonUsuario.setForeground(new java.awt.Color(255, 255, 255));
        botonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N
        botonUsuario.setText("Usuario");
        botonUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        botonUsuario.setBorderPainted(false);
        botonUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonUsuario.setEnabled(false);
        botonUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonUsuario.setIconTextGap(15);

        botonProducto.setBackground(new java.awt.Color(141, 114, 231));
        botonProducto.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        botonProducto.setForeground(new java.awt.Color(255, 255, 255));
        botonProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/producto.png"))); // NOI18N
        botonProducto.setText("Producto");
        botonProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        botonProducto.setBorderPainted(false);
        botonProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonProducto.setIconTextGap(13);
        botonProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductoActionPerformed(evt);
            }
        });

        botonProveedor.setBackground(new java.awt.Color(141, 114, 231));
        botonProveedor.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        botonProveedor.setForeground(new java.awt.Color(255, 255, 255));
        botonProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proveedor.png"))); // NOI18N
        botonProveedor.setText("Proveedor");
        botonProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        botonProveedor.setBorderPainted(false);
        botonProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonProveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonProveedor.setIconTextGap(13);
        botonProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProveedorActionPerformed(evt);
            }
        });

        botonReporte.setBackground(new java.awt.Color(141, 114, 231));
        botonReporte.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        botonReporte.setForeground(new java.awt.Color(255, 255, 255));
        botonReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporte.png"))); // NOI18N
        botonReporte.setText("Reporte");
        botonReporte.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        botonReporte.setBorderPainted(false);
        botonReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonReporte.setIconTextGap(16);
        botonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteActionPerformed(evt);
            }
        });

        botonAcercaDe.setBackground(new java.awt.Color(141, 114, 231));
        botonAcercaDe.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        botonAcercaDe.setForeground(new java.awt.Color(255, 255, 255));
        botonAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desarrollador.png"))); // NOI18N
        botonAcercaDe.setText("Acerca de");
        botonAcercaDe.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        botonAcercaDe.setBorderPainted(false);
        botonAcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAcercaDe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonAcercaDe.setIconTextGap(16);
        botonAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcercaDeActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(141, 114, 231));
        botonSalir.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        botonSalir.setText("Cerrar Sesión");
        botonSalir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        botonSalir.setBorderPainted(false);
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonSalir.setIconTextGap(14);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(botonPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(botonUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(botonProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(botonProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(botonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(botonAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorEmpresaUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadorEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(nombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(separadorEmpresaUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(separadorEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(botonPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(botonUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(botonProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(botonProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(botonReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(botonAcercaDe, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(140, 140, 140))
        );

        header.setBackground(new java.awt.Color(141, 114, 231));
        header.setForeground(new java.awt.Color(0, 0, 0));
        header.setPreferredSize(new java.awt.Dimension(732, 150));

        tituloBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        tituloBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloBienvenido.setText("¡Bienvenido!");

        tituloDate.setForeground(new java.awt.Color(0, 0, 0));
        tituloDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDate.setText("Hoy es {dayname} {day} de {month} de {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloDate, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addComponent(tituloBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tituloBienvenido)
                .addGap(32, 32, 32)
                .addComponent(tituloDate)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setForeground(new java.awt.Color(0, 0, 0));
        contenido.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // Cambia el idioma de los botones del cuadro de diálogo JOptionPane a español
        UIManager.put("OptionPane.yesButtonText", "Sí");
        UIManager.put("OptionPane.noButtonText", "No");

        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea cerrar "
                + "sesión?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            // Cerrar sesión y volver a la ventana de inicio de sesión (Login).
            dispose(); // Cierra la ventana actual (DashboardUser).
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPrincipalActionPerformed

    private void botonProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductoActionPerformed
        ShowJPanel(new Producto());
    }//GEN-LAST:event_botonProductoActionPerformed

    private void botonProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProveedorActionPerformed
        ShowJPanel(new Proveedor());
    }//GEN-LAST:event_botonProveedorActionPerformed

    private void botonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteActionPerformed
        ShowJPanel(new Reporte());
    }//GEN-LAST:event_botonReporteActionPerformed

    private void botonAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcercaDeActionPerformed
        ShowJPanel(new Desarrollador());
    }//GEN-LAST:event_botonAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
            UIManager.put("Component.focusWidth", 1);
            UIManager.put("ScrollBar.thumbArc", 999);
            FlatLaf.setGlobalExtraDefaults(Collections.singletonMap("@accentColor", "#5A3AC9"));
            FlatIntelliJLaf.setup();

        } catch (Exception e) {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton botonAcercaDe;
    private javax.swing.JButton botonPrincipal;
    private javax.swing.JButton botonProducto;
    private javax.swing.JButton botonProveedor;
    private javax.swing.JButton botonReporte;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonUsuario;
    private static javax.swing.JPanel contenido;
    private javax.swing.JPanel header;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nombreEmpresa;
    private javax.swing.JSeparator separadorEmpresa;
    private javax.swing.JSeparator separadorEmpresaUltimo;
    private javax.swing.JLabel tituloBienvenido;
    private javax.swing.JLabel tituloDate;
    // End of variables declaration//GEN-END:variables
}
