/**
 * Desarrollador.java
 * Esta clase representa un panel de la interfaz de usuario que muestra información sobre el 
 * desarrollador de la aplicación.
 * Proporciona detalles de contacto y enlaces a perfiles en redes sociales del desarrollador.
 * También, permite abrir enlaces externos en el navegador predeterminado y enviar correos electrónicos.
 * Este archivo es parte del paquete "com.views".
 *
 * Este archivo es parte de InversionesRT.
 *
 * InversionesRT es software libre: puedes redistribuirlo y/o modificarlo
 * bajo los términos de la Licencia Pública General GNU publicada por
 * la Free Software Foundation, ya sea la versión 3 de la Licencia, o
 * (a su elección) cualquier versión posterior.
 *
 * InversionesRT se distribuye con la esperanza de que sea útil,
 * pero SIN NINGUNA GARANTÍA; incluso sin la garantía implícita de
 * COMERCIABILIDAD o APTITUD PARA UN PROPÓSITO PARTICULAR. Consulta la
 * Licencia Pública General GNU para más detalles.
 *
 * Deberías haber recibido una copia de la Licencia Pública General GNU
 * junto con [nombre del proyecto]. En caso contrario, consulta
 * <https://www.gnu.org/licenses/gpl-3.0.html>.
 */
package com.views;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URLEncoder;

public class Desarrollador extends javax.swing.JPanel {

    public Desarrollador() {
        initComponents();
        initStyles();

        informacionVersionGNU.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirEnlace(evt);
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                informacionVersionGNU.setForeground(new java.awt.Color(141, 114, 231)); // Cambia el color del texto cuando se pasa el mouse
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                informacionVersionGNU.setForeground(new java.awt.Color(90, 58, 201)); // Restaura el color original del texto al salir del mouse
            }
        });

        informacionVersionGNU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    }

    private void initStyles() {
        tituloEmpresa.putClientProperty("FlatLaf.style", "font: $h1.font");
        tituloEmpresa.setForeground(new java.awt.Color(90, 58, 201));

        controlVersion.putClientProperty("FlatLaf.styleClass", "h4");
        controlVersion.setForeground(Color.GRAY);

        tituloDesarrollador.putClientProperty("FlatLaf.styleClass", "h2");
        tituloDesarrollador.setForeground(Color.DARK_GRAY);

        datosDesarrollador.putClientProperty("FlatLaf.styleClass", "h2");
        datosDesarrollador.setForeground(Color.GRAY);

        informacionApp.putClientProperty("FlatLaf.styleClass", "h3");
        informacionApp.setForeground(Color.GRAY);

        informacionVersion.putClientProperty("FlatLaf.styleClass", "h3");
        informacionVersion.setForeground(Color.GRAY);

        informacionVersionGNU.putClientProperty("FlatLaf.styleClass", "h3");
        informacionVersionGNU.setForeground(new java.awt.Color(90, 58, 201));

        informacionCodigoFuente.putClientProperty("FlatLaf.styleClass", "h3");
        informacionCodigoFuente.setForeground(Color.GRAY);
    }

    // Agregar el directorio del github con el txt de la licencia.
    private void abrirEnlace(java.awt.event.MouseEvent evt) {
        try {
            String url = "https://github.com/TheUndertakerrr/InversionesRT/blob/main/LICENSE.txt";
            Desktop.getDesktop().browse(new URI(url));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        tituloEmpresa = new javax.swing.JLabel();
        controlVersion = new javax.swing.JLabel();
        tituloDesarrollador = new javax.swing.JLabel();
        datosDesarrollador = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonEnlaceFacebook = new javax.swing.JButton();
        botonEnlaceYouTube = new javax.swing.JButton();
        botonEnlaceTwitter = new javax.swing.JButton();
        botonEnlaceTelegram = new javax.swing.JButton();
        botonEnlaceGoogle = new javax.swing.JButton();
        informacionApp = new javax.swing.JLabel();
        informacionVersion = new javax.swing.JLabel();
        informacionVersionGNU = new javax.swing.JLabel();
        informacionCodigoFuente = new javax.swing.JLabel();
        botonEnlaceGithub = new javax.swing.JButton();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(0, 0, 0));

        tituloEmpresa.setText("Inversiones R.T Desktop");

        controlVersion.setText("versión 1.0");

        tituloDesarrollador.setText("Developed by:");

        datosDesarrollador.setText("Manuel A. Marcano");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botonEnlaceFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook.png"))); // NOI18N
        botonEnlaceFacebook.setBorderPainted(false);
        botonEnlaceFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEnlaceFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnlaceFacebookActionPerformed(evt);
            }
        });

        botonEnlaceYouTube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/youtube.png"))); // NOI18N
        botonEnlaceYouTube.setBorderPainted(false);
        botonEnlaceYouTube.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEnlaceYouTube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnlaceYouTubeActionPerformed(evt);
            }
        });

        botonEnlaceTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/twitter.png"))); // NOI18N
        botonEnlaceTwitter.setBorderPainted(false);
        botonEnlaceTwitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEnlaceTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnlaceTwitterActionPerformed(evt);
            }
        });

        botonEnlaceTelegram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telegram.png"))); // NOI18N
        botonEnlaceTelegram.setBorderPainted(false);
        botonEnlaceTelegram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEnlaceTelegram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnlaceTelegramActionPerformed(evt);
            }
        });

        botonEnlaceGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gmail.png"))); // NOI18N
        botonEnlaceGoogle.setBorderPainted(false);
        botonEnlaceGoogle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEnlaceGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnlaceGoogleActionPerformed(evt);
            }
        });

        informacionApp.setText("Aplicación Oficial para el Control y Gestión de Inventarios.");

        informacionVersion.setText("Este software está licenciado bajo las versiones");

        informacionVersionGNU.setText("GNU GPL versión 3.");

        informacionCodigoFuente.setText("El código fuente está disponible en GitHub");

        botonEnlaceGithub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/github.png"))); // NOI18N
        botonEnlaceGithub.setBorderPainted(false);
        botonEnlaceGithub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEnlaceGithub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnlaceGithubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloDesarrollador)
                            .addComponent(informacionApp)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(informacionVersion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(informacionVersionGNU))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(informacionCodigoFuente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonEnlaceGithub))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(datosDesarrollador)
                                .addGap(35, 35, 35)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEnlaceFacebook)
                                .addGap(18, 18, 18)
                                .addComponent(botonEnlaceYouTube)
                                .addGap(18, 18, 18)
                                .addComponent(botonEnlaceTwitter)
                                .addGap(18, 18, 18)
                                .addComponent(botonEnlaceTelegram)
                                .addGap(18, 18, 18)
                                .addComponent(botonEnlaceGoogle))))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(controlVersion))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(tituloEmpresa)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tituloEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(controlVersion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonEnlaceYouTube, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEnlaceFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEnlaceTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEnlaceTelegram, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEnlaceGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(81, 81, 81))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(tituloDesarrollador)
                        .addGap(37, 37, 37)
                        .addComponent(datosDesarrollador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(informacionApp)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(informacionVersion)
                    .addComponent(informacionVersionGNU))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informacionCodigoFuente)
                    .addComponent(botonEnlaceGithub, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnlaceFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnlaceFacebookActionPerformed
        String facebookUrl = "https://www.facebook.com/theunderrrtaker/";
        openURL(facebookUrl);
    }//GEN-LAST:event_botonEnlaceFacebookActionPerformed

    private void botonEnlaceTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnlaceTwitterActionPerformed
        String twitterUrl = "https://twitter.com/TheUnderrrtaker";
        openURL(twitterUrl);
    }//GEN-LAST:event_botonEnlaceTwitterActionPerformed

    private void botonEnlaceGithubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnlaceGithubActionPerformed
        String githubUrl = "https://github.com/TheUndertakerrr/InversionesRT.git";
        openURL(githubUrl);
    }//GEN-LAST:event_botonEnlaceGithubActionPerformed

    private void botonEnlaceYouTubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnlaceYouTubeActionPerformed
        String youtubeUrl = "https://www.youtube.com/channel/UCX8UVqeLynfHhyUZFVUjxw";
        openURL(youtubeUrl);
    }//GEN-LAST:event_botonEnlaceYouTubeActionPerformed

    private void botonEnlaceTelegramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnlaceTelegramActionPerformed
        String telegramUrl = "https://t.me/TheUndertakerrr";
        openURL(telegramUrl);
    }//GEN-LAST:event_botonEnlaceTelegramActionPerformed

    private void botonEnlaceGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnlaceGoogleActionPerformed
        String gmailUrl = "manuelmarcano52@gmail.com";
        String subject = "¡Hola! Estoy interesado(a) en conversar contigo";

        sendEmail(gmailUrl, subject);
    }//GEN-LAST:event_botonEnlaceGoogleActionPerformed

    public static void sendEmail(String email, String subject) {
        try {
            String uri = "mailto:" + email + "?subject=" + URLEncoder.encode(subject, "UTF-8");
            Desktop.getDesktop().browse(new URI(uri));
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }

    public static void openURL(String url) {
        try {
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(url));
            } else {
                System.out.println("No se puede abrir la URL en el navegador predeterminado.");
            }
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton botonEnlaceFacebook;
    private javax.swing.JButton botonEnlaceGithub;
    private javax.swing.JButton botonEnlaceGoogle;
    private javax.swing.JButton botonEnlaceTelegram;
    private javax.swing.JButton botonEnlaceTwitter;
    private javax.swing.JButton botonEnlaceYouTube;
    private javax.swing.JLabel controlVersion;
    private javax.swing.JLabel datosDesarrollador;
    private javax.swing.JLabel informacionApp;
    private javax.swing.JLabel informacionCodigoFuente;
    private javax.swing.JLabel informacionVersion;
    private javax.swing.JLabel informacionVersionGNU;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tituloDesarrollador;
    private javax.swing.JLabel tituloEmpresa;
    // End of variables declaration//GEN-END:variables
}
