/**
 * Principal.java
 * Esta clase representa el panel principal de la interfaz, donde se muestran varios párrafos de texto 
 * y una imagen.
 * Este archivo es parte del paquete "com.views".
 *
 * Este archivo es parte de InversionesRT.
 *
 * InversionesRT es software libre: puedes redistribuirlo y/o modificarlo
 * bajo los términos de la Licencia Pública General GNU publicada por
 * la Free Software Foundation, ya sea la versión 3 de la Licencia, o
 * (a su elección) cualquier versión posterior.
 *
 * InversionesRT se distribuye con la esperanza de que sea útil,
 * pero SIN NINGUNA GARANTÍA; incluso sin la garantía implícita de
 * COMERCIABILIDAD o APTITUD PARA UN PROPÓSITO PARTICULAR. Consulta la
 * Licencia Pública General GNU para más detalles.
 *
 * Deberías haber recibido una copia de la Licencia Pública General GNU
 * junto con [nombre del proyecto]. En caso contrario, consulta
 * <https://www.gnu.org/licenses/gpl-3.0.html>.
 */
package com.views;

import java.awt.Color;

public class Inicio extends javax.swing.JPanel {

    public Inicio() {
        initComponents();
        initStyles();
    }

    // Estilos y tipografías de los párrafos.
    public void initStyles(){
        parrafo_1.putClientProperty( "FlatLaf.style", "large" );
        parrafo_1.setForeground(new java.awt.Color(51, 51, 51));
        
        parrafo_2.putClientProperty( "FlatLaf.style", "large" );
        parrafo_2.setForeground(new java.awt.Color(51, 51, 51));
        
        parrafo_3.putClientProperty( "FlatLaf.style", "large" );
        parrafo_3.setForeground(new java.awt.Color(51, 51, 51));
        
        parrafo_4.putClientProperty( "FlatLaf.style", "large" );
        parrafo_4.setForeground(new java.awt.Color(51, 51, 51));
        
        parrafo_5.putClientProperty( "FlatLaf.style", "large" );
        parrafo_5.setForeground(new java.awt.Color(51, 51, 51));
        
        parrafo_6.putClientProperty( "FlatLaf.style", "large" );
        parrafo_6.setForeground(new java.awt.Color(51, 51, 51));
        
        parrafo_7.putClientProperty( "FlatLaf.style", "large" );
        parrafo_7.setForeground(Color.BLACK);
        
        parrafo_8.putClientProperty( "FlatLaf.style", "large" );
        parrafo_8.setForeground(Color.BLACK);
        
        parrafo_9.putClientProperty( "FlatLaf.style", "large" );
        parrafo_9.setForeground(Color.BLACK);
        
        parrafo_10.putClientProperty( "FlatLaf.style", "large" );
        parrafo_10.setForeground(Color.BLACK);
        
        parrafo_11.putClientProperty( "FlatLaf.style", "large" );
        parrafo_11.setForeground(Color.BLACK);
        
        parrafo_12.putClientProperty( "FlatLaf.style", "large" );
        parrafo_12.setForeground(Color.BLACK);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        parrafo_1 = new javax.swing.JLabel();
        parrafo_2 = new javax.swing.JLabel();
        parrafo_3 = new javax.swing.JLabel();
        parrafo_4 = new javax.swing.JLabel();
        parrafo_5 = new javax.swing.JLabel();
        parrafo_6 = new javax.swing.JLabel();
        parrafo_7 = new javax.swing.JLabel();
        parrafo_8 = new javax.swing.JLabel();
        parrafo_9 = new javax.swing.JLabel();
        parrafo_10 = new javax.swing.JLabel();
        parrafo_11 = new javax.swing.JLabel();
        parrafo_12 = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 490));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(0, 0, 0));

        parrafo_1.setText("Sistema para el Control y Gestión del Inventario de la empresa Inversiones R.T. 2013, C.A. con el propósito de realizar las");

        parrafo_2.setText("actividades con mayor fluidez y contar con un sistema que permita tener un mejor manejo de los documentos y");

        parrafo_3.setText("materiales que se disponen.");

        parrafo_4.setText("Esta herramienta le permitirá llevar un control completo y detallado de su Inventario.");

        parrafo_5.setText("Tendrá acceso a distintos módulos en el menú lateral dependiendo de su nivel dentro del sistema para las tareas");

        parrafo_6.setText("específicas que desee realizar, como lo son:");

        parrafo_7.setText("- Usuario.");

        parrafo_8.setText("- Producto.");

        parrafo_9.setText("- Proveedor.");

        parrafo_10.setText("- Ayuda.");

        parrafo_11.setText("- Acerca de.");

        parrafo_12.setText("- Cerrar Sesión.");

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/construcción.png"))); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parrafo_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parrafo_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parrafo_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parrafo_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parrafo_9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parrafo_12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parrafo_11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(parrafo_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parrafo_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parrafo_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parrafo_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parrafo_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(parrafo_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parrafo_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parrafo_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(parrafo_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(parrafo_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parrafo_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(parrafo_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(parrafo_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(parrafo_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(parrafo_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(parrafo_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(parrafo_12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94))
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel parrafo_1;
    private javax.swing.JLabel parrafo_10;
    private javax.swing.JLabel parrafo_11;
    private javax.swing.JLabel parrafo_12;
    private javax.swing.JLabel parrafo_2;
    private javax.swing.JLabel parrafo_3;
    private javax.swing.JLabel parrafo_4;
    private javax.swing.JLabel parrafo_5;
    private javax.swing.JLabel parrafo_6;
    private javax.swing.JLabel parrafo_7;
    private javax.swing.JLabel parrafo_8;
    private javax.swing.JLabel parrafo_9;
    // End of variables declaration//GEN-END:variables
}